@startuml
!include estilo.iuml
left to right direction
skinparam nodesep 25
skinparam ranksep 90
actor Visitante
rectangle "Landing Page — Semana Tecnológica UCPel 2026" {
  usecase "Consultar Programação" as UC1
  usecase "Visualizar Palestrantes" as UC2
  usecase "Buscar Localização" as UC5
  usecase "Entrar em Contato" as UC6
  usecase UC3 as "Consultar Oficinas
--
<i>extension points</i>
Quero participar"
  usecase "Realizar Inscrição" as UC4
  usecase "Validar Dados\ndo Formulário" as UC7
}
Visitante -- UC1
Visitante -- UC2
Visitante -- UC5
Visitante -- UC6
Visitante -- UC3
Visitante -- UC4
UC4 .up.> UC3 : <<extend>>
note right on link
  <b>Condição:</b> {visitante clica em
  "Quero participar" no card da oficina}
  <b>Ponto de extensão:</b> Quero participar
end note
UC4 ..> UC7 : <<include>>
@enduml
